title: Yang Fu
description: Yang Fu is a PhD student at Fudan University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yangfu.site" # the base hostname & protocol for your site
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  math_engine: mathjax
